### PR TITLE
Hooks feature: Scenario for general before hook

### PR DESCRIPTION
**Pull request by tooky**
There is lots of great documentation on the wiki, thought we could try to bring some of it over into the feature descriptions.

### CODE REVIEW

**Comment by jbpros** [comment]
Thank you, that scenario is great! You were our first donator :)

Now I'm wondering what should be put into the feature descriptions. I like expressing the good old business value there. We should discuss it.

**Comment by tooky** [comment]
Thanks :-)

Expressing the business value definitely has its place!

But if we want to make these features the definitive documentation for cucumber, then it makes sense to be a bit more descriptive!

The rspec features on relishapp (http://relishapp.com/rspec/) do a great job of being specification and documentation.

**Comment by jbpros** [comment]
That is clearly the direction we are heading at now. What about starting the feature description with the three typical lines followed by a blank line and the more descriptive documentation paragraph(s)?

Or is the reason of existence of each Cucumber functionality obvious enough to not explicitly write them down? Then this might unnecessarily clutter up the documentation.

**Comment by jbpros** [comment]
i suggest we discuss this on the cukes ML.

**Pull request merged**
